local RV = {}

-- definition constants
RV.MAX_MEMORY_WORD = 65536 -- 256 kiB limit
RV.MAX_MEMORY_SIZE = RV.MAX_MEMORY_WORD * 4
RV.MAX_FREQ_MULTIPLIER = 34 -- default_frame_rate * 34 <= logisim_max_simulation_hertz
RV.MAX_TEMPERATURE = 120.0
RV.MOD_IDENTIFIER = "FREECOMPUTER"
RV.EXTENSIONS = {"RV32I", "RV32C", "RV32M"}
RV.ILLEGAL_INSTRUCTION = "ILLEGAL"
RV.CODE_NAME = "ATOMIC"

RV.TYPE_R = 1
RV.TYPE_I = 2
RV.TYPE_S = 3
RV.TYPE_U = 4
RV.TYPE_B = 5
RV.TYPE_J = 6

return RV
